Grille audit flash
copsae/outils-audits-accessibilite pull request #3
Opened 2021-12-01 16:33 UTC by juliemoynatPro

2021-12-16 11:31 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +    - « **NA** » (« Non applicable ») : Soit aucun élément dans la page ne concerne la règle, soit le seul contenu qui concerne la règle est exempté ([cf. RGAA sur les contenus exemptés pour les site
Ici, je me demande si on ne devrait pas se cantonner à "aucun élément dans la page ne concerne la règle" vu qu'on n'est pas dans un objectif de conformité pure.

En même temps, si c'est un site concerné par le périmètre de la loi, c'est probablement mieux de prévoir les exemptions et dérogations. Qu'en penses-tu @lbuffet-pro ?

2021-12-16 13:45 UTC, lbuffet-pro requested changes
Sur le fichier même de la grille : 
- sur l'onglet "Règles", il manque de mise en forme (le titre global ne s'étend pas sur toute la largeur, il manque des bordures aux colonnes "Problème détecté" et "Impact")
-  Dans l'onglet calcul, je m'interroge sur la nécessite de mettre le total de règles avec au moins un problème. De même, la colonne "nombre de règles à évaluer" nécessite qu'on remplisse chaque cellule à la main et qu'on pense à les mettre à jour, ce qui me semble complexe pour une info somme toute peu intéressante non ?
- Dans l'onglet "Échantillon" : à quoi correspond "Contexte de l'audit" ?

2021-12-16 13:45 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +- **Calculs :** L’audit flash n’a pas pour objectif de se substituer à un audit de conformité. Il est moins exhaustif. Ainsi, afin de ne pas semer le trouble avec des résultats trompeurs, nous avons
"qui serait alors utilisé à tort"

2021-12-16 13:45 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +- **Calculs :** L’audit flash n’a pas pour objectif de se substituer à un audit de conformité. Il est moins exhaustif. Ainsi, afin de ne pas semer le trouble avec des résultats trompeurs, nous avons
"comme cela a pu se voir pour d'autres audits simplifiés" : tu fais référence à quelque chose de précis ? Je trouve que ça sonne un peu "on pointe du doigt ce qui a été mal fait mais on n'assume pas au point de le dire explicitement", je trouve ça étrange.

2021-12-16 13:45 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +    - « **Non** » : Aucun problème n’a été détecté dans la page pour la règle en question (ce qui ne veut pas dire qu’il n’y en a pas pour les critères RGAA concernés mais que, via l’audit flash, on
Est-ce qu'on ne garderait pas le pronom "nous" ? : "nous n'en avons pas détecté"

2021-12-16 13:45 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +    - Chaque problème peut avoir un impact sur les utilisateurs et utilisatrices différent. Ainsi, il convient d’indiquer, entre crochets et avant d’expliquer le problème, l’impact supposé :
Je comprends pas ce que tu veux dire ici : "Chaque problème peut avoir un impact différent sur les utilisateurs et utilisatrices différent"

2021-12-16 13:49 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +- **Calculs :** L’audit flash n’a pas pour objectif de se substituer à un audit de conformité. Il est moins exhaustif. Ainsi, afin de ne pas semer le trouble avec des résultats trompeurs, nous avons
Ok, je vais retirer parce que je suis pas sûre que ce soit vraiment bien de dire ici qu'on voit ça dans l'Observatoire avec les audits de 25 critères ou encore qu'il existe des déclarations basées sur des audits automatisés…

2021-12-16 13:54 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +    - « **Non** » : Aucun problème n’a été détecté dans la page pour la règle en question (ce qui ne veut pas dire qu’il n’y en a pas pour les critères RGAA concernés mais que, via l’audit flash, on
Le pronom "nous" c'est quand on parle de nous mais le "on" ici ne parle pas de nous. Il parle de la personne qui fait l'audit. Du coup, je vais remplacer "on" par "l'auditeur ou l'auditrice".

2021-12-16 13:55 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +    - Chaque problème peut avoir un impact sur les utilisateurs et utilisatrices différent. Ainsi, il convient d’indiquer, entre crochets et avant d’expliquer le problème, l’impact supposé :
euh oui, j'ai dû ajouter "sur les utilisateurs et utilisatrices" après coup

2021-12-16 13:56 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +        - **Mineur** = impact faible : le problème ne gêne pas l’accès à l’information (exemple : l’élement `<title>` ne contient pas le nom du site mais le nom du site est bien présent dans l’en-têt
@lbuffet-pro ces définitions te semblent bien ?

2021-12-16 14:04 UTC, juliemoynatPro commented
> Sur le fichier même de la grille :
> 
>     * sur l'onglet "Règles", il manque de mise en forme (le titre global ne s'étend pas sur toute la largeur, il manque des bordures aux colonnes "Problème détecté" et "Impact")
> 
>     * Dans l'onglet calcul, je m'interroge sur la nécessite de mettre le total de règles avec au moins un problème. De même, la colonne "nombre de règles à évaluer" nécessite qu'on remplisse chaque cellule à la main et qu'on pense à les mettre à jour, ce qui me semble complexe pour une info somme toute peu intéressante non ?
> 
>     * Dans l'onglet "Échantillon" : à quoi correspond "Contexte de l'audit" ?

Le fichier est encore en cours. 😁

- Onglet "Règles" traité.
- Onglet "Calculs" : non c'est automatisé, bien sûr.
    - Le nombre de règles restant à évaluer permet de s'assurer qu'on n'a pas oublié des statuts "NT".
    - Je comprends pas ce qui dérange avec le total. L'idée est d'avoir une idée du nombre de problèmes mais sachant qu'on peut en mettre plusieurs par case, je n'ai pas de meilleure solution. Ça donne une idée. Ensuite, libre à nous de compter le nombre total de problèmes à la main si on veut et si on nous le demande.
- "Contexte de l'audit" c'est juste pour dire dans quel contexte cet audit est demandé. C'est un champ libre donc on peut ici y renseigner si cet audit doit avoir des préconisations ou pas en complément, par exemple et aussi si l'objectif est un audit diagnostic ou un audit pour corriger à destination des équipes projet. (à noter que ça existe dans la grille officielle pour l'audit de conformité donc je garde le formalisme initial sur ce point)

2021-12-17 08:50 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +        - **Mineur** = impact faible : le problème ne gêne pas l’accès à l’information (exemple : l’élement `<title>` ne contient pas le nom du site mais le nom du site est bien présent dans l’en-têt
Oui ça me paraît bien.

2021-12-17 09:11 UTC, lbuffet-pro requested changes

2021-12-17 09:11 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +# Grille d’audit flash (checklist) basé sur le RGAA
"Basée" non ? Je sais pas si on parle de l'audit ou de la grille fait.

2021-12-17 09:11 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +Cette grille a été réalisé avec LibreOffice Calc. Nous ne garantissons pas son fonctionnement avec Microsoft Excel.
"réalisée"

2021-12-17 09:11 UTC, lbuffet-pro commented on audit-flash-rgaa/README.md
> +    - Indiquer ensuite le problème relevé mais sans faire la préconisation de correction. Un tableur n’est pas approprié pour y faire figurer autant d’informations. Il vaut mieux mettre les préconisa
Je pense qu'ici on pourra du coup mettre un renvoi vers ton document `.md` sur les préconisations.

2021-12-17 09:17 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +# Grille d’audit flash (checklist) basé sur le RGAA
Je parle de l'audit qui est basé sur le RGAA.

2021-12-17 09:17 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +Cette grille a été réalisé avec LibreOffice Calc. Nous ne garantissons pas son fonctionnement avec Microsoft Excel.
roooh

2021-12-17 10:30 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +    - « **NA** » (« Non applicable ») : Soit aucun élément dans la page ne concerne la règle, soit le seul contenu qui concerne la règle est exempté ([cf. RGAA sur les contenus exemptés pour les site
Vu ensemble, on reste iso RGAA.

2021-12-17 10:33 UTC, juliemoynatPro commented on audit-flash-rgaa/README.md
> +    - Indiquer ensuite le problème relevé mais sans faire la préconisation de correction. Un tableur n’est pas approprié pour y faire figurer autant d’informations. Il vaut mieux mettre les préconisa
Fait

2021-12-17 10:36 UTC, lbuffet-pro approved these changes

2021-12-17 10:52 UTC, merged